from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[no-redef]

from . import paths


DEFAULT_EXCLUDES = (
    "**/node_modules/**/node_modules/**",  # avoid pathological deep nests
    "**/.git/**",
    "**/target/**",
    "**/dist/**",
    "**/build/**",
    "**/.next/**",
    "**/__pycache__/**",
    "**/.venv/**/Lib/**",
    "**/venv/**/Lib/**",
)


@dataclass
class ScanConfig:
    roots: list[Path] = field(default_factory=list)
    excludes: list[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDES))
    deep_scan: bool = True
    ecosystems: list[str] = field(
        default_factory=lambda: ["npm", "pypi", "cargo", "go", "rubygems"]
    )


@dataclass
class FeedsConfig:
    osv: bool = True
    openssf: bool = True
    aikido: bool = True
    refresh_minutes: int = 30
    max_age_hours: int = 24       # if feeds are older than this, auto-refresh on launch


@dataclass
class DiscordAlertConfig:
    webhook: str = ""


@dataclass
class ToastAlertConfig:
    enabled: bool = True


@dataclass
class ReportAlertConfig:
    dir: Path | None = None


@dataclass
class AlertsConfig:
    discord: DiscordAlertConfig = field(default_factory=DiscordAlertConfig)
    toast: ToastAlertConfig = field(default_factory=ToastAlertConfig)
    report: ReportAlertConfig = field(default_factory=ReportAlertConfig)


@dataclass
class DaemonConfig:
    interval_minutes: int = 60


@dataclass
class Config:
    scan: ScanConfig = field(default_factory=ScanConfig)
    feeds: FeedsConfig = field(default_factory=FeedsConfig)
    alerts: AlertsConfig = field(default_factory=AlertsConfig)
    daemon: DaemonConfig = field(default_factory=DaemonConfig)
    path: Path | None = None


def _expand(p: str | Path) -> Path:
    return Path(p).expanduser().resolve() if p else Path()


def load(path: Path | None = None) -> Config:
    cfg_path = path or paths.config_path()
    if not cfg_path.exists():
        return Config(path=cfg_path)
    with open(cfg_path, "rb") as f:
        data = tomllib.load(f)

    scan_d = data.get("scan", {})
    feeds_d = data.get("feeds", {})
    alerts_d = data.get("alerts", {})
    daemon_d = data.get("daemon", {})

    scan = ScanConfig(
        roots=[_expand(r) for r in scan_d.get("roots", []) if r],
        excludes=list(scan_d.get("excludes", DEFAULT_EXCLUDES)),
        deep_scan=bool(scan_d.get("deep_scan", True)),
        ecosystems=list(scan_d.get("ecosystems", ["npm", "pypi", "cargo", "go", "rubygems"])),
    )
    feeds = FeedsConfig(
        osv=bool(feeds_d.get("osv", True)),
        openssf=bool(feeds_d.get("openssf", True)),
        aikido=bool(feeds_d.get("aikido", True)),
        refresh_minutes=int(feeds_d.get("refresh_minutes", 30)),
        max_age_hours=int(feeds_d.get("max_age_hours", 24)),
    )
    discord_d = alerts_d.get("discord", {})
    toast_d = alerts_d.get("toast", {})
    report_d = alerts_d.get("report", {})
    report_dir_raw = report_d.get("dir", "")
    alerts = AlertsConfig(
        discord=DiscordAlertConfig(webhook=str(discord_d.get("webhook", ""))),
        toast=ToastAlertConfig(enabled=bool(toast_d.get("enabled", True))),
        report=ReportAlertConfig(dir=_expand(report_dir_raw) if report_dir_raw else None),
    )
    daemon = DaemonConfig(interval_minutes=int(daemon_d.get("interval_minutes", 60)))
    return Config(scan=scan, feeds=feeds, alerts=alerts, daemon=daemon, path=cfg_path)


def write_default(path: Path | None = None, root_guess: Path | None = None) -> Path:
    cfg_path = path or paths.config_path()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    root_line = f'roots = ["{root_guess.as_posix()}"]' if root_guess else 'roots = ["~/code"]'
    template = f"""# taintwatch config
# Generated by `taintwatch config init`. Edit freely.

[scan]
{root_line}
excludes = []                          # extra globs to skip
deep_scan = true                       # also walk node_modules / site-packages
ecosystems = ["npm", "pypi", "cargo", "go", "rubygems"]

[feeds]
osv = true
openssf = true
aikido = true                          # set false if your org requires redistributable-only feeds
refresh_minutes = 30                   # daemon polling cadence
max_age_hours = 24                     # if feeds are older than this on launch, auto-refresh in background

[alerts.discord]
webhook = ""                           # paste a Discord webhook URL to enable

[alerts.toast]
enabled = true

[alerts.report]
dir = ""                               # empty = default state-dir/reports

[daemon]
interval_minutes = 60
"""
    cfg_path.write_text(template, encoding="utf-8")
    return cfg_path
